global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "fastapi_app"
    static_configs:
      - targets: ["web:8000"] # 'web' is the service name in docker-compose.yml
    metrics_path: "/metrics" # FastAPI app will expose metrics on /metrics endpoint

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"] # 'node-exporter' is the service name

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"] # Assuming you'll add cAdvisor later for container metrics
